version: "3.9"
services:
  gist-monitor:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - redis

  redis:
    image: redis:6.0.6-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data: