---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gist-monitor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gist-monitor
  template:
    metadata:
      labels:
        app: gist-monitor 
    spec:
      containers:
      - name: gist-monitor
        image: gcr.io/gist-monitor-311718/gist-monitor:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
          - containerPort: 3000    
        env:
          - name: REDIS_HOST
            value: redis-master
          - name: REDIS_PORT
            value: "6379"    
---
apiVersion: v1
kind: Service
metadata:
  name: gist-monitor-service
spec:
  type: LoadBalancer
  selector:
    app: gist-monitor
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
